# Generated by Django 5.2.3 on 2025-06-18 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='Titulo da Issue', max_length=500)),
                ('description', models.TextField(help_text='Descrição detalhada da Issue')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', help_text='Status da Issue', max_length=20)),
                ('priority', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', help_text='Prioridade da Issue', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, help_text='suário responsável por resolver a Issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='usuário que reportou a tarefa', on_delete=django.db.models.deletion.PROTECT, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('body', models.TextField(help_text='Conteudo do Comentario')),
                ('user', models.ForeignKey(help_text='User qual percente ao comentario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(help_text='Issue qual percente ao comentario', on_delete=django.db.models.deletion.CASCADE, to='api.issuemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='Nome do Projeto', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do projeto', null=True)),
                ('owner', models.ForeignKey(help_text='Usuário que gerencia o projeto', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issuemodel',
            name='project',
            field=models.ForeignKey(help_text='Projeto ao qual a issue pertence', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.projectmodel'),
        ),
    ]
